#!/bin/bash

./script/render article articles/go_concurrency_alternative_haskells_race.md > index.html
./script/render article articles/macro_expansion_with_slime.md > posts/macro_expansion_with_slime.html
./script/render article articles/ruby_blocks_with_lisp_macros.md > posts/ruby_blocks_with_lisp_macros.html
./script/render article articles/go_concurrency_alternative_haskells_race.md > posts/go_concurrency_alternative_haskells_race.html
./script/render archive > archive.html
